//generated by Duckyspark https://github.com/toxydose/Duckyspark

#include "DigiKeyboard.h"
#define KEY_ESC     41
#define KEY_BACKSPACE 42
#define KEY_TAB     43
#define KEY_PRT_SCR 70
#define KEY_DELETE  76

void setup() {

DigiKeyboard.delay(5000);
DigiKeyboard.sendKeyStroke(0);
DigiKeyboard.UIKEY_D);
DigiKeyboard.sendKeyStroke(KEY_ESC,MOD_CONTROL_LEFT);
DigiKeyboard.print(F("https://i.imgflip.com/1dv8ac.jpg"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(100);
// REM Opens up window and goes to a image I created xD
DigiKeyboard.sendKeyStroke(KEY_S,MOD_CONTROL_LEFT);
DigiKeyboard.print(F("%userprofile%")); DigiKeyboard.print(char(92)); DigiKeyboard.print(F("Desktop")); DigiKeyboard.print(char(92)); DigiKeyboard.print(F("QUACKED"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
// REM saving the picture to the user Desktop, pic name QUACKED...
DigiKeyboard.delay(100);
DigiKeyboard.sendKeyStroke(KEY_D,MOD_GUI_LEFT);
// REM shows desktop
DigiKeyboard.sendKeyStroke(KEY_R,MOD_GUI_LEFT);
DigiKeyboard.print(F("%userprofile%")); DigiKeyboard.print(char(92)); DigiKeyboard.print(F("Desktop")); DigiKeyboard.print(char(92)); DigiKeyboard.print(F("QUACKED.png"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
// REM opens the png file
DigiKeyboard.sendKeyStroke(MOD_GUI_RIGHT);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.sendKeyStroke(KEY_F4,MOD_ALT_RIGHT);
// REM sets the background, and closes.
DigiKeyboard.sendKeyStroke(KEY_D,MOD_GUI_LEFT);
DigiKeyboard.sendKeyStroke(MOD_GUI_RIGHT);
DigiKeyboard.print(F("v"));
DigiKeyboard.print(F("d"));
// REM I know its basic but tell what you think im only 14 and this is my first "program" thanks Darren

}


void loop() {

}

