//generated by Duckyspark https://github.com/toxydose/Duckyspark

#include "DigiKeyboard.h"
#define KEY_ESC     41
#define KEY_BACKSPACE 42
#define KEY_TAB     43
#define KEY_PRT_SCR 70
#define KEY_DELETE  76

void setup() {

DigiKeyboard.delay(5000);
DigiKeyboard.sendKeyStroke(0);
DigiKeyboard.sendKeyStroke(KEY_D,MOD_GUI_LEFT);
DigiKeyboard.delay(500);
DigiKeyboard.sendKeyStroke(KEY_PRT_SCR);
DigiKeyboard.delay(100);
DigiKeyboard.sendKeyStroke(MOD_GUI_RIGHT);
DigiKeyboard.delay(300);
DigiKeyboard.print(F("V"));
DigiKeyboard.delay(40);
DigiKeyboard.print(F("D"));
DigiKeyboard.delay(300);
DigiKeyboard.sendKeyStroke(KEY_R,MOD_GUI_LEFT);
DigiKeyboard.delay(700);
DigiKeyboard.print(F("mspaint"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(1200);
DigiKeyboard.sendKeyStroke(KEY_V,MOD_CONTROL_LEFT);
DigiKeyboard.delay(500);
DigiKeyboard.sendKeyStroke(KEY_F,MOD_ALT_RIGHT);
DigiKeyboard.print(F("c"));
DigiKeyboard.delay(1000);
DigiKeyboard.print(F("%userprofile%")); DigiKeyboard.print(char(92)); DigiKeyboard.print(F("a.bmp"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(500);
DigiKeyboard.sendKeyStroke(KEY_F,MOD_ALT_RIGHT);
DigiKeyboard.delay(400);
DigiKeyboard.print(F("F"));
DigiKeyboard.delay(1000);
DigiKeyboard.sendKeyStroke(KEY_F4,MOD_ALT_RIGHT);
DigiKeyboard.delay(300);
DigiKeyboard.sendKeyStroke(KEY_D,MOD_GUI_LEFT);
DigiKeyboard.delay(300);
DigiKeyboard.SHIFTKEY_F10);
DigiKeyboard.delay(100);
DigiKeyboard.KEY_ARROW_DOWN);
DigiKeyboard.delay(100);
DigiKeyboard.KEY_ARROW_RIGHTT);
DigiKeyboard.delay(100);
DigiKeyboard.KEY_ARROW_UP);
DigiKeyboard.delay(100);
DigiKeyboard.sendKeyStroke(KEY_ENTER);

}


void loop() {

}

